#!/usr/bin/env python

import subprocess as sp
import sys
import readline

# TODO: maybe add completion

readline.parse_and_bind('tab: complete')

while True:
    try:
        word = raw_input('d> ')
    except (EOFError, KeyboardInterrupt):
        print 'bye'
        sys.exit(0)
    if not word.strip():
        continue
    sp.call(['dict', word])
